baseURL: "https://michaelreichenbach.de/"
title: Michael Reichenbach
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-N05EXWL5RF

minify:
    disableXML: true
    minifyOutput: true

disqusShortname: michaelreichenbach

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary for search

permalinks:
    posts: /posts/:filename/

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Michael Reichenbach | Blog
    description: "My blog about technical problems, solutions and code."
    keywords: [Blog]
    author: Silthus
    # author: ["Me", "You"] # multiple authors
    images: ["/logo.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: true
    ShowRelatedContent: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    ShowRssButtonInSectionTermList: true
    comments: true
    hidemeta: false
    hideSummary: false
    hideFooter: true
    showtoc: true
    tocopen: false

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        safari_pinned_tab: "/safari-pinned-tab.svg"

    label:
        text: " "
        icon: /logo.png
        iconHeight: 40

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "Welcome \U0001F44B"
        subtitle: "...to my blog!"
        imageUrl: "/profile.jpeg"
        imageWidth: 200
        imageHeight: 200
        imageTitle: it's me
        buttons:
            - name: Posts
              url: posts
            - name: Categories
              url: categories
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Welcome \U0001F44B"
        Content: "... to my blog"

    socialIcons:
        - name: github
          url: "https://github.com/Silthus"
        - name: linkedin
          url: "https://linkedin.com/in/michael-reichenbach"
        - name: twitter
          url: "https://twitter.com/silthus"
        - name: email
          url: "mailto:me@silthus.net"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false
        responsiveImages: true

    editPost:
        URL: "https://github.com/Silthus/michaelreichenbach.de/edit/main/content"
        Text: "Edit" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 5
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 10
        - identifier: search
          name: Search
          url: /search/
          weight: 15
        - identifier: archive
          name: Archive
          url: /archive/
          weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai